### PR TITLE
Added some syntactic sugar for listening to components as well as IDs

### PR DESCRIPTION
**Pull request by jamesadevine**
Means you can do something like:

```cpp
#include "CircuitPlayground.h"
#include "CodalDmesg.h"
#include "HIDKeyboard.h"

CircuitPlayground cplay;
CodalUSB usb;
USBHIDKeyboard keyboard;


void send_a(Event)
{
    keyboard.type('a');
}

int main()
{
    usb.add(keyboard);
    usb.start();

    cplay.messageBus.listen(cplay.buttonA, DEVICE_BUTTON_EVT_CLICK, send_a);

    int state = 0;
    while(1)
    {
        state = !state;
        cplay.io.led.setDigitalValue(state);
        cplay.sleep(500);
    }
}
```

### CODE REVIEW

**Comment by jamesadevine** [comment]
@mmoskal any concerns? Flash size increase?

**Comment by mmoskal** [comment]
It's all inline so no flash increase.

**Comment by mmoskal** [comment]
I mean technically you need one more `ldrh r0, [r0, #4]` or whatever on call but really...

**Comment by jamesadevine** [comment]
Thanks!

**Pull request merged**
