### PR TITLE
Add optional user_data in CodalFiber

### PR DESCRIPTION
**Pull request by mmoskal**
@finneyj does this seem to make sense?

I want to use it to implement thread-local data.

### CODE REVIEW

**Comment by finneyj** [comment]
hi @mmoskal 

Yep, makes sense to me. what use for this do you have in mind?

**Comment by mmoskal** [comment]
I'm using it to keep track which parts of stack are Typescript and which c++ for my garbage collector. I also plan to use it for keeping track of try-catch handlers.

**Comment by finneyj** [comment]
yep - perfect use. I wondered about doing a primitive GC on the micro:bit side years ago, and would have used this approach too.

**Comment by mmoskal** [comment]
I'm not sure I'll use the GC on the microbit, would need to really count the bytes...

**Pull request merged**
