### PR TITLE
Add ASCII keymap

### PR DESCRIPTION
**Pull request by deanm1278**
hi @jamesadevine, I have added some keymap functionality (as well as a bit of general refactoring of the HID keyboard code to make it a little less bad).

a constructor has been added:
`USBHIDKeyboard::USBHIDKeyboard(const keySequence *m, uint16_t mapLen, void (*delayfn)(int))`

This takes a keymap, the number of elements in the keymap, and a delay callback.
an example program is:
```
#include "CircuitPlayground.h"
#include "Keymap.h"

CircuitPlayground cplay;

void cplayDelay(int ms) { cplay.sleep(ms); }

#include "HIDKeyboard.h"
CodalUSB usb;
USBHIDKeyboard hid(keymap_ascii, 128, cplayDelay);

static const char *string_descriptors[] = {
    "Example Corp.", "PXT Device", "42424242",
};

int main()
{
    usb.stringDescriptors = string_descriptors;
    usb.add(hid);
    usb.start();

    //we need a bit of a delay for USB
    cplay.sleep(500);

    while(1)
    {
        hid.type("hello world!!\n");
        cplay.sleep(500);
    }
}
```

This just prints "hello world!!" over and over again.

looking at the file `Keymap.h`, a `keySequence` is just a sequence of `key` structs, and a keymap is an array of `keySequence` structs.

the ASCII keymap is implemented in the file `KeymapASCII.cpp`. Each key sequence is defined, and then they are placed in the correct order to create the full ASCII table keymap.

a key sequence can be arbitrarily long, so if users need to define a keymap that presses and releases many keys in a specific order to create say a Japanese character or something that is possible.

For example you could define a not very useful keymap of specific sequences as:

```
//press and release h,e,l,l,o keys individually
static const key seq_hello[] = { 
{ .reg = KEYMAP_KEY_DOWN | KEY_H },
{ .reg = KEYMAP_KEY_UP | KEY_H },

{ .reg = KEYMAP_KEY_DOWN | KEY_E },
{ .reg = KEYMAP_KEY_UP | KEY_E },

{ .reg = KEYMAP_KEY_DOWN | KEY_L },
{ .reg = KEYMAP_KEY_UP | KEY_L },

{ .reg = KEYMAP_KEY_DOWN | KEY_L },
{ .reg = KEYMAP_KEY_UP | KEY_L },

{ .reg = KEYMAP_KEY_DOWN | KEY_O },
{ .reg = KEYMAP_KEY_UP | KEY_O },
};

//press and release w,o,r,l,d keys individually
static const key seq_world[] = { 
{ .reg = KEYMAP_KEY_DOWN | KEY_W },
{ .reg = KEYMAP_KEY_UP | KEY_W },

{ .reg = KEYMAP_KEY_DOWN | KEY_O },
{ .reg = KEYMAP_KEY_UP | KEY_O },

{ .reg = KEYMAP_KEY_DOWN | KEY_R },
{ .reg = KEYMAP_KEY_UP | KEY_R },

{ .reg = KEYMAP_KEY_DOWN | KEY_L },
{ .reg = KEYMAP_KEY_UP | KEY_L },

{ .reg = KEYMAP_KEY_DOWN | KEY_D },
{ .reg = KEYMAP_KEY_UP | KEY_D },
};

const keySequence keymap_hello_world[] = {
	KEYMAP_REGISTER(seq_hello), 
	KEYMAP_REGISTER(seq_world), 
};
```

### CODE REVIEW

**Comment by jamesadevine** [comment]
> hi @jamesadevine, I have added some keymap functionality (as well as a bit of general refactoring of the HID keyboard code to make it a little less bad).

@deanm1278 you are too hard on yourself, it was great, and this contribution is also greatly appreciated (I was just about to make some coffee, and code the night away). 😄 Since this is the first time we are thinking about a HID abstraction in CODAL, the APIs and code are likely to change.

In this PR, there are a lot of improvements, however, there are a few things I'd like to change before a merge. Would you mind if I take tomorrow to make a few changes?

**Comment by deanm1278** [comment]
@jamesadevine have at it!

**Comment by pelikhan** [comment]
@deanm1278 I'm working on HID Joystick support in Adafruit editor. Do you have a CODAL sample for it?

* common packages: https://github.com/microsoft/pxt-common-packages/tree/hidjoystick
* adafruit repo: https://github.com/microsoft/pxt-adafruit/tree/joystick

**Comment by jamesadevine** [comment]
@deanm1278 Is there anything special I have to do on Mac to get the cplay to act as a keyboard? Windows works fine, Mac does not. I don't think the Mac initialises the CPlays' Endpoint.

**Comment by jamesadevine** [comment]
Hi @deanm1278 , hope you had a good weekend, sorry this took me longer than a couple of days... term is booting back up at the University!

I've pushed a commit that adds a couple of nice things for CODAL, such as `ManagedString` interfaces and the use of `fiber_sleep` (we should really add some docs for developers such as yourself).

Although the diff is large, all I've done is moved your code about really... it's largely the same.

Here's some code to show each of the APIs:

```cpp
#include "CircuitPlayground.h"
#include "USB_HID_Keys.h"
#include "HIDKeyboard.h"

CircuitPlayground cplay;

CodalUSB usb;
USBHIDKeyboard hid;

static const char *string_descriptors[] = {
    "Example Corp.", "PXT Device", "42424242",
};

void typeLetters(Event)
{
    hid.type("Hello!");
}

void mediaKey(Event)
{
    hid.press(VolumeUp);
    cplay.sleep(1000);
    hid.press(Home);
    cplay.sleep(1000);
    hid.press(F1Key);
}

static const Key seq_hello[] = {
    { .reg = KEYMAP_KEY_DOWN | KEY_H },
    { .reg = KEYMAP_KEY_UP | KEY_H },

    { .reg = KEYMAP_KEY_DOWN | KEY_E },
    { .reg = KEYMAP_KEY_UP | KEY_E },

    { .reg = KEYMAP_KEY_DOWN | KEY_L },
    { .reg = KEYMAP_KEY_UP | KEY_L },

    { .reg = KEYMAP_KEY_DOWN | KEY_L },
    { .reg = KEYMAP_KEY_UP | KEY_L },

    { .reg = KEYMAP_KEY_DOWN | KEY_O },
    { .reg = KEYMAP_KEY_UP | KEY_O }
};

const KeySequence keymap_hello_world[] = {
	KEYMAP_REGISTER(seq_hello)
};

void writeSequence(Event)
{
    hid.type(keymap_hello_world);
}

int main()
{
    usb.stringDescriptors = string_descriptors;
    usb.add(hid);
    usb.start();

    //we need a bit of a delay for USB
    cplay.sleep(500);

    cplay.messageBus.listen(DEVICE_ID_BUTTON_A,DEVICE_BUTTON_EVT_CLICK,typeLetters);
    cplay.messageBus.listen(DEVICE_ID_BUTTON_B,DEVICE_BUTTON_EVT_CLICK,mediaKey);
    cplay.messageBus.listen(DEVICE_ID_BUTTON_AB,DEVICE_BUTTON_EVT_CLICK,writeSequence);

    release_fiber();
}
```

**Comment by jamesadevine** [comment]
@deanm1278 see anything that could be changed/improved? Also, any thoughts on the Mac issue?

**Comment by deanm1278** [comment]
Looks good! I'm gonna look into the mac issue now. It seems to be a problem
with the codal HID implementation in general. I should be able to track it
down today.

**Comment by jamesadevine** [comment]
@deanm1278 I have a hint as to what it might be...

bAlternateSetting should be zero for the first interface descriptor (according to my windows based diagnostics). Perhaps mac cares about this more...?

**Comment by deanm1278** [comment]
yup that fixed it! Check latest commit all descriptors are fixed and tested
working on mac and windows

**Comment by deanm1278** [comment]
@pelikhan sorry for the delay, wanted to get things working on mac as well. below is a codal sample for the joystick/gamepad. I'm not super great with codal so I just followed james provided example.
Press the A button to press button 1 on the gamepad
Release the A button to release button 1
Press the B button to move analog joystick 0 on the gamepad to position 50
Release the B button to move analog joystick 0 on the gamepad back to the center

```
#include "CircuitPlayground.h"
#include "HIDJoystick.h"

CircuitPlayground cplay;

CodalUSB usb;
USBHIDJoystick hid;

static const char *string_descriptors[] = {
    "Example Corp.", "PXT Device", "42424242",
};

void buttonADown(Event)
{
   //push button 1 down
   hid.buttonDown(1);
}

void buttonAUp(Event)
{
   //release button 1
   hid.buttonUp(1);
}

void joystickSet(Event)
{
    hid.move(0, 50, 0);
}

void joystickRelease(Event)
{
    hid.move(0, -50, 0);
}

int main()
{
    usb.stringDescriptors = string_descriptors;
    usb.add(hid);
    usb.start();

    //we need a bit of a delay for USB
    cplay.sleep(500);

    cplay.messageBus.listen(DEVICE_ID_BUTTON_A,DEVICE_BUTTON_EVT_DOWN,buttonADown);
    cplay.messageBus.listen(DEVICE_ID_BUTTON_A,DEVICE_BUTTON_EVT_UP,buttonAUp);

    cplay.messageBus.listen(DEVICE_ID_BUTTON_B,DEVICE_BUTTON_EVT_DOWN,joystickSet);
    cplay.messageBus.listen(DEVICE_ID_BUTTON_B,DEVICE_BUTTON_EVT_UP,joystickRelease);

    release_fiber();
}
```
I tested this with the joytester free application:
http://www.softpedia.com/get/System/System-Miscellaneous/Joystick-Tester.shtml

**Comment by jamesadevine** [comment]
Great work, thanks a lot @deanm1278 !

**Comment by ladyada** [comment]
nice work everyone, this is going to be really great with all the HID interfaces 😁😁😁

**Comment by pelikhan** [comment]
Have these been tested cross plat?

**Comment by ladyada** [comment]
@pelikhan hiya are you asking me or @deanm1278 ?

**Comment by pelikhan** [comment]
I tried the joystick interface but couldn’t get it to work (and ran out of time for this). A C++ sample for each HID interface would be wonderful so I could backtrack what I got wrong.

**Comment by ladyada** [comment]
kk where should we commit the examples to?

**Comment by pelikhan** [comment]
@james?

________________________________

**Comment by jamesadevine** [comment]
@pelikhan @ladyada Samples can be placed in this [folder](https://github.com/lancaster-university/codal-circuit-playground/tree/master/samples), in the target - It might be best to create a usb folder for usb samples. On first compile, samples will be copied into a 'samples' folder in the root of the build tree.

**Comment by deanm1278** [comment]
ok I can add some examples in that folder. @pelikhan you tried the example I posted in this thread 3 days ago using the most recent master branch and it did not work? What platform are you using and how are you testing?

**Comment by pelikhan** [comment]
I tried to cook my own example for the joystick and integrate it in the MakeCode editor so I was looking for a C++ test program to pinpoint where in the stack thing went bad.

**Comment by deanm1278** [comment]
ok @pelikhan here's the example from earlier in the thread if you want to try:

Press the A button to press button 1 on the gamepad
Release the A button to release button 1
Press the B button to move analog joystick 0 on the gamepad to position 50
Release the B button to move analog joystick 0 on the gamepad back to the center
```
#include "CircuitPlayground.h"
#include "HIDJoystick.h"

CircuitPlayground cplay;

CodalUSB usb;
USBHIDJoystick hid;

static const char *string_descriptors[] = {
    "Example Corp.", "PXT Device", "42424242",
};

void buttonADown(Event)
{
   //push button 1 down
   hid.buttonDown(1);
}

void buttonAUp(Event)
{
   //release button 1
   hid.buttonUp(1);
}

void joystickSet(Event)
{
    hid.move(0, 50, 0);
}

void joystickRelease(Event)
{
    hid.move(0, -50, 0);
}

int main()
{
    usb.stringDescriptors = string_descriptors;
    usb.add(hid);
    usb.start();

    //we need a bit of a delay for USB
    cplay.sleep(500);

    cplay.messageBus.listen(DEVICE_ID_BUTTON_A,DEVICE_BUTTON_EVT_DOWN,buttonADown);
    cplay.messageBus.listen(DEVICE_ID_BUTTON_A,DEVICE_BUTTON_EVT_UP,buttonAUp);

    cplay.messageBus.listen(DEVICE_ID_BUTTON_B,DEVICE_BUTTON_EVT_DOWN,joystickSet);
    cplay.messageBus.listen(DEVICE_ID_BUTTON_B,DEVICE_BUTTON_EVT_UP,joystickRelease);

    release_fiber();
}
```
I tested this with the joytester free application:
http://www.softpedia.com/get/System/System-Miscellaneous/Joystick-Tester.shtml

I will make some more complete examples for all HID APIs and commit to the folder James recommended soon.

**Comment by deanm1278** [comment]
@pelikhan @jamesadevine some examples have been added here: https://github.com/adafruit/codal-circuit-playground/tree/master/samples/USB

The keyboard example is the one james provided. The others are very simple and loop through the functions of each API

**Pull request merged**
