### PR TITLE
Remove outdated JACDAC abstraction

### PR DESCRIPTION
**Pull request by jamesadevine**
This PR removes all outdated JACDAC code from codal-core. Please visit the https://aka.ms/jacdac website or any of our many repositories [microsoft/jacdac](https://github.com/microsoft/jacdac) [microsoft/jacdac-ts](https://github.com/microsoft/jacdac-ts) and [microsoft/jacdac-c](https://github.com/microsoft/jacdac-c) to discover the new home for JACDAC.

### CODE REVIEW

**Review by mmoskal — APPROVED** [review]

**Comment by jamesadevine** [comment]
In addition to this pull request, I have made PRs to the following:
 - common processor libraries:
     - lancaster-university/codal-stm32#18
     - lancaster-university/codal-nrf52#20
     - lancaster-university/codal-samd#28
- target libraries:
    - lancaster-university/codal-itsybitsy-m4#5
    - lancaster-university/codal-circuit-playground#10
    - lancaster-university/codal-big-brainpad#5

I believe this should cover the entirety of CODAL. I've built each of the above targets too (including microbit-v2) to ensure my changes are good. Is there anything I've missed @mmoskal @finneyj?

When merged, this PR will close lancaster-university/codal-core#125 and microsoft/jacdac#64

**Comment by mmoskal** [comment]
Sounds good!

**Comment by finneyj** [comment]
Thanks @jamesadevine - makes sense. No point having old versions lying around when we have up to date TypeScript and Python implementations.

Would welcome any new jacdac goodies in codal in the future of course!

**Comment by jamesadevine** [comment]
Thanks @finneyj :smile: watch out for future PRs!

**Pull request merged**
