### PR TITLE
Apply patch for broadcast driver disconnection

### PR DESCRIPTION
**Pull request by jamesadevine**
The logic driver ignored disconnect / connect events for broadcast drivers. There was also a risk that by connecting and disconnecting broadcast drivers from the bus, you could crash a jacdac device.

cc @pelikhan 

Just need to test.

### CODE REVIEW

**Comment by pelikhan** [comment]
Love broadcast drivers

**Comment by jamesadevine** [comment]
Apparently I left my devices at work... 🙄

**Comment by jamesadevine** [comment]
Not a good patch, will have to fix tomorrow (out of time today).

**Comment by jamesadevine** [comment]
This should work @pelikhan.

**Comment by pelikhan** [comment]
Thanks!

**Pull request merged**
