### PR TITLE
Support for Serial NOR Flash File System (SNORFS)

### PR DESCRIPTION
**Pull request by mmoskal**
This isn't ready yet. Creating PR to facilitate discussion.

TODO:
* [x] change `addFile()` to supply constant string or callback, with a parameter
* [x] add delay-start mechanism in `CodalUSB`; use it in `addFiles()`
* [ ] when device is on battery, and USB cable is re-plugged, we should call `addFiles()` again
* [ ] maybe add a software way of doing the same (call `addFiles()`, do a software USB reset)
* [ ] think about progress callback

When testing this, best use the following bootloader:
[uf2-samd-1.24.zip](https://github.com/lancaster-university/codal-core/files/1571537/uf2-samd-1.24.zip)

This will let you drop any UF2 file on the "CODAL" drive (as well as "CPLAYBOOT")

### CODE REVIEW

**Comment by mmoskal** [comment]
@ladyada writes:
> hmm i'd like to try to maintain some compatibility with the FS that ships on the board, if possible! makes USB easier as well....

If we allow the OS direct access to the filesystem via blocks, we cannot safely update files while CPX is connected to a computer. One needs some calls for mounting and unmounting. Also, we would most likely need a separate drive for flashing (UF2) and exposing SPI flash, which is confusing to the user.

I plan to expose SNORFS files on the same drive as will be using for UF2 flashing. The only way to update them will be with a specially formed UF2 file. This way the web app will be able to make sure users don't drop random WAV files on the drive etc.

> what if we keep the FAT FS BUT you get/create one big file, say "MakeCode.bin" or .dat or whatnot, that is 512KB fixed size. then you write all you want to the file, and you wont have to wearlevel it because it isn't being constantly erased/updated

I'm not sure what would be the advantage of this - MP and Arduino wouldn't be able to access the contents of that file, and it would involve considerable amount of FAT support code on our side.

**Comment by tannewt** [comment]
Hi hi! This wear leveling stuff looks really cool. I have a couple higher level questions to give me context for the design decisions of SNORFS.

- What is the interaction the user sees on the host computer?
- Will the host be able to write to the FS or be read-only?
- If its read-only, then whats the need for multiple files?
- Will the FS only be accessible from the MakeCode website or will it work in the file explorer?
- If its the website, what tech under the hood are you using for the USB transport?
- What will the format of the files be? Will it be user configurable?

Thanks!

**Comment by mmoskal** [comment]
The host will access the SNORFS files via virtual file system, similar to the UF2 bootloader. The files will be read in native format (i.e., not in UF2). Files can be in any format the application wishes (we think CSV and WAV will be popular).

The simplest way to transfer files from host to the device is to generate a program that writes the files and compile it to UF2. Then just flash it and it will create files. There are of course size limitations in this approach.

For example, we could ship a UF2 file, that writes a set of pre-defined WAV files, which then would be accessible from the subsequently flashed programs.

In future, we should be able to accept specially formatted UF2 files that will write the SPI flash directly (which would remove size limitations). The problem is that it wouldn't work with bootloader, only with the application-level MSC.

Multiple files are useful because: a) you might want to log many separate things, b) you might want to rotate log files, c) you can use files for storing various settings (best to use small files).

**Comment by finneyj** [comment]
Hi @mmoskal 

Thanks for working on this and for sharing.

I've just done a quick scan of your code here, and only one broad question at the moment beyond those discussed already above. I guess you saw the on-chip FLASH file system from the micro:bit? This was built on the same design principles you have here and optimized for similar things too (FAT16 esque approach, wear levelling, posix API, abstract file object model). I was going to generalize that for codal at some point also, and it would be ideal if we could align the two as much as possible (both to deduplicate code and to make sure APIs are as consistent as possible so that we can reuse higher level code we develop  across as many platforms as possible. 

I know you're focussed on SPI/Block devices here, but did you have any thoughts about what the relationship between these might be?

**Comment by finneyj** [comment]
oops - forgot to share links:

https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitFileSystem.cpp
https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitFile.cpp

**Comment by mmoskal** [comment]
My main concern is that Microbit FS buffers writes. When I think of a user-friendly logging API, it doesn't buffer writes. However, forcing a flash after every write will cause high amount of churn in the directory page - every time I add a few bytes to the log file, the FS will need to create a new directory entry.

Secondary concern is that scratch page is somewhat more difficult to do with SPI, and also the double-erase (of updated page and scratch page) is kind of slow. Also, this would probably apply to 4k SPI sectors, which are slower to erase than 64k sectors.

I think, for internal flash the best structure would be a linked list of content (i.e., blocks with length and pointer to the next block in file), and not storing length in metadata. Also note that on NRF52 pages are 4k, and on STM32F4 the pages where FS would likely be are 128k.

**Comment by finneyj** [comment]
Thanks Michal - yes, this is a real issue. I was chatting to the ARM guys about this a few months ago too (most FS implementations suffer in one way or another. I think the ARM guys are starting to look at journalling file systems, which seems overkill to me). 

In MicrotBitFS we worked around this a little by making the writeback cache optional and small by default (16 bytes) and directory entries can be invalidated without causing a flash erase (on nrf51 this only causes a page erase every twenty or so updates, which is not ideal but manageable).

The pathological case we were most concerned about was when kids rewind and partially overwrite a file (and this could happen byte by byte). This can churn through flash erase/burn cycles very quickly, which is why we buffered a bit - a compromise between stateless storage and wear leveling.

How do you think SNORFS would cope with this pathological case?

**Comment by mmoskal** [comment]
@finneyj  SNORFS doesn't handle the pathological issue at all. The operations supported are:
* create empty file
* delete file
* append data at the end
* read at any offset
* list all files in file system, including their sizes

There are no directories and no writing in the middle of the file. I might add two "categories" of files - regular and hidden, where hidden wouldn't show in virtual FAT. I guess hidden files will be the ones with ':' somewhere in the name.

There's an additional optimization for a delete-create-append cycle, however every time you have to specify the entire data you want to write. Essentially, I envision the following scenarios:
* log files (CSV etc)
* resources (WAV etc)
* small config files (one would usually use separate files for separate settings)

Usually, the reason you want to write in the middle of the file, is because it consists of separate parts. In that case, use separate files.

**Comment by ladyada** [comment]
Interesting blog post perhaps? https://os.mbed.com/blog/entry/littlefs-high-integrity-embedded-fs/

**Comment by mmoskal** [comment]
@ladyada thank you for pointing out little fs!

I read through it (the github page), and it looks quite promising. They seem to have put much more thought into fault tolerance that I did. The logging use case isn't as optimized (as far as I understand, every flush requires a flash (4k block erase)), and minimal disk file size is 4.5k. OTOH it does support directories and writing in the middle of the file (which, however, requires re-writing everything that comes after, so I guess is of small utility).

**Comment by mmoskal** [comment]
@finneyj @jamesadevine Do you want this merged?

To summarize, this implements the following:
* various USB interface fixes (both here and `codal-samd21`)
* generic SPI flash interface
* implementation of USB Mass Storage Class
* FAT file system implemented virtually (called Ghost FAT, since Virtual FAT is something else)
* SNORFS, a SPI file system
* GhostSNORFS - SNORFS exposed via Ghost FAT

I understand the contentious part is SNORFS (and by extension GhostSNORFS), so I can move it out to pxt-common-packages. What do you say?

I'm asking because I want to add WebUSB support, which requires at least the USB fixes from here.

CC @pelikhan @tballmsft @abchatra

**Pull request merged**
